dist: xenial
language: python
cache:
  directories:
  - $HOME/.cache/pypoetry/virtualenvs
matrix:
  include:
  - python: "2.7"
    env: CELERY_VERSION=3.1
  - python: "2.7"
    env: CELERY_VERSION=4.0
  - python: "2.7"
    env: CELERY_VERSION=4.1
  - python: "2.7"
    env: CELERY_VERSION=4.2
  - python: "2.7"
    env: CELERY_VERSION=4.3
  - python: "3.4"
    env: CELERY_VERSION=3.1
  - python: "3.4"
    env: CELERY_VERSION=4.0
  - python: "3.4"
    env: CELERY_VERSION=4.1
  - python: "3.4"
    env: CELERY_VERSION=4.2
  - python: "3.4"
    env: CELERY_VERSION=4.3
  - python: "3.5"
    env: CELERY_VERSION=3.1
  - python: "3.5"
    env: CELERY_VERSION=4.0
  - python: "3.5"
    env: CELERY_VERSION=4.1
  - python: "3.5"
    env: CELERY_VERSION=4.2
  - python: "3.5"
    env: CELERY_VERSION=4.3
  - python: "3.6"
    env: CELERY_VERSION=4.1
  - python: "3.6"
    env: CELERY_VERSION=4.2
  - python: "3.6"
    env: CELERY_VERSION=4.3
  - python: "3.7"
    env: CELERY_VERSION=4.3
before_install:
  - pip install poetry==0.12.17
install:
  - poetry add celery==$CELERY_VERSION
  - poetry add codecov
script:
  - poetry run pytest
  - poetry run black --check .
after_success:
  - poetry run codecov
