language: python
# python versions
matrix:
  include:
  - python: "2.7"
    env: CELERY_VERSION=3.1
  - python: "2.7"
    env: CELERY_VERSION=4.0
  - python: "2.7"
    env: CELERY_VERSION=4.1
  - python: "2.7"
    env: CELERY_VERSION=4.2
  # - python: "3.3"
  #   env: CELERY_VERSION=3.1
  - python: "3.4"
    env: CELERY_VERSION=3.1
  - python: "3.4"
    env: CELERY_VERSION=4.0
  - python: "3.4"
    env: CELERY_VERSION=4.1
  - python: "3.4"
    env: CELERY_VERSION=4.2
  - python: "3.5"
    env: CELERY_VERSION=3.1
  - python: "3.5"
    env: CELERY_VERSION=4.0
  - python: "3.5"
    env: CELERY_VERSION=4.1
  - python: "3.5"
    env: CELERY_VERSION=4.2
  - python: "3.6"
    env: CELERY_VERSION=4.1
  - python: "3.6"
    env: CELERY_VERSION=4.2
# command to install dependencies
install:
  - pip install pytest pytest-mock
  - pip install celery==$CELERY_VERSION requests ephem
  - if [[ $TRAVIS_PYTHON_VERSION == '2.7' || $TRAVIS_PYTHON_VERSION == '3.3' ]]; then pip install responses; else pip install vcrpy; fi
  - pip install codecov
# command to run tests
script: pytest
# combinations to include
after_success:
  - codecov
