dist: xenial
language: python
cache:
  pip: true
  directories:
  - "$HOME/.cache/pypoetry"
matrix:
  include:
  - python: "2.7"
    env: CELERY_VERSION=3.1
  - python: "2.7"
    env: CELERY_VERSION=4.0
  - python: "2.7"
    env: CELERY_VERSION=4.1
  - python: "2.7"
    env: CELERY_VERSION=4.2
  - python: "2.7"
    env: CELERY_VERSION=4.3
  - python: "3.5"
    env: CELERY_VERSION=3.1
  - python: "3.5"
    env: CELERY_VERSION=4.0
  - python: "3.5"
    env: CELERY_VERSION=4.1
  - python: "3.5"
    env: CELERY_VERSION=4.2
  - python: "3.5"
    env: CELERY_VERSION=4.3
  - python: "3.6"
    env: CELERY_VERSION=4.1
  - python: "3.6"
    env: CELERY_VERSION=4.2
  - python: "3.6"
    env: CELERY_VERSION=4.3
  - python: "3.7"
    env: CELERY_VERSION=4.3
before_install:
  - pip install poetry==0.12.17
install:
  - env -u VIRTUAL_ENV poetry add celery==$CELERY_VERSION
  - env -u VIRTUAL_ENV poetry add codecov
script:
  - env -u VIRTUAL_ENV poetry run pytest
  - if [[ $TRAVIS_PYTHON_VERSION == 3.7 ]]; then (env -u VIRTUAL_ENV poetry run black --check .); fi
after_success:
  - env -u VIRTUAL_ENV poetry run codecov
