"""Version information."""
__title__ = 'celery-slack'
__description__ = 'A Slack extension for Celery.'
__url__ = 'https://github.com/crflynn/celery-slack'
__version__ = '0.1.0'
__author__ = 'Christopher Flynn'
__author_email__ = 'crf204@gmail.com'
__license__ = 'MIT'
__copyright__ = 'Copyright 2017 Christopher Flynn'
__docs_copyright__ = '2017 Christopher Flynn'
